name: Make
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-pandoc
        run: sudo apt install pandoc -y --no-install-recommends

      - name: make
        run: make site

      - name: create-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: site-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: true

      - name: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./site.tar.gz
          asset_name: site.tar.gz
          asset_content_type: application/x-zip
